// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package db

import (
	"context"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (
    user_id,
    name,
    storage_key,
    size,
    content_type
) VALUES (
             $1,
             $2,
             $3,
             $4,
             $5
         )
    RETURNING id, user_id, name, storage_key, size, content_type, created_at, updated_at
`

type CreateFileParams struct {
	UserID      int64
	Name        string
	StorageKey  string
	Size        int64
	ContentType string
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.UserID,
		arg.Name,
		arg.StorageKey,
		arg.Size,
		arg.ContentType,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.StorageKey,
		&i.Size,
		&i.ContentType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files
WHERE id = $1 AND user_id = $2
`

type DeleteFileParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteFile(ctx context.Context, arg DeleteFileParams) error {
	_, err := q.db.Exec(ctx, deleteFile, arg.ID, arg.UserID)
	return err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, user_id, name, storage_key, size, content_type, created_at, updated_at
FROM files
WHERE id = $1
`

func (q *Queries) GetFileByID(ctx context.Context, id int64) (File, error) {
	row := q.db.QueryRow(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.StorageKey,
		&i.Size,
		&i.ContentType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFilesByUserID = `-- name: ListFilesByUserID :many
SELECT id, user_id, name, storage_key, size, content_type, created_at, updated_at
FROM files
WHERE user_id = $1
ORDER BY id DESC
`

func (q *Queries) ListFilesByUserID(ctx context.Context, userID int64) ([]File, error) {
	rows, err := q.db.Query(ctx, listFilesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.StorageKey,
			&i.Size,
			&i.ContentType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
