// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type File struct {
	ID          int64
	UserID      int64
	Name        string
	StorageKey  string
	Size        int64
	ContentType string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}
